# Generated by Django 2.2.10 on 2021-08-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210802_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='user_id',
            field=models.ManyToManyField(blank=True, to='polls.User'),
        ),
    ]
