# Generated by Django 2.2.10 on 2021-08-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_quiz_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='user_id',
            new_name='user',
        ),
    ]
