# Generated by Django 2.2.10 on 2021-08-02 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210802_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='user_id',
            new_name='user',
        ),
    ]
