# Generated by Django 2.2.10 on 2021-08-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20210802_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='user',
            new_name='users',
        ),
    ]
