# Generated by Django 2.2.10 on 2021-08-03 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_availablechoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailableChoice',
        ),
    ]
