# Generated by Django 2.2.10 on 2021-08-03 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_delete_availablechoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(default='')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_choices', to='polls.Question')),
            ],
            options={
                'verbose_name_plural': 'available_choices',
                'db_table': 'available_choice',
            },
        ),
        migrations.CreateModel(
            name='UserChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(default='')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_choices', to='polls.Question')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.User')),
            ],
            options={
                'verbose_name_plural': 'user_choices',
                'db_table': 'user_choice',
            },
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
