# Generated by Django 2.2.10 on 2021-08-03 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20210803_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availablechoice',
            options={'verbose_name_plural': 'Доступные пользователю выборы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Опросы'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='userchoice',
            options={'verbose_name_plural': 'Выборы пользователя'},
        ),
    ]
